import "pkg:/source/services/InvidiousSettings.bs"

@asynctask
function InvidiousPublicInstancesTask(input as object) as object
    ' TODO: Move this to a better place
    ' Caching backup instances in this task to avoid having to do it in the UI thread
    ' Should be moved to a better place
    backupInstances = InvidiousSettings.FetchBackupInstances()

    return {
        backupInstances: backupInstances
    }
end function
