function SetPalette(dialog as object)
    palette = createObject("roSGNode", "RSGPalette")
    palette.colors = {
        DialogBackgroundColor: "#242424FF"
        DialogFocusColor: "#CECECEFF"
        DialogFocusItemColor: "#202020FF"
        ' bs:disable-next-line LINT3023
        DialogSecondaryTextColor: "#EBEBEBFF"
        DialogSecondaryItemColor: "#FF1C30FF"
        ' bs:disable-next-line LINT3023
        DialogTextColor: "#EBEBEBFF"
    }
    dialog.palette = palette
end function
