function SetPalette()
    palette = createObject("roSGNode", "RSGPalette")
    palette.colors = {
        DialogBackgroundColor: "#242424FF",
        DialogFocusColor: "#CECECEFF",
        DialogFocusItemColor: "#202020FF",
        DialogSecondaryTextColor: "#F8F8F8FF",
        DialogSecondaryItemColor: "0xFF1C30FF",
        DialogTextColor: "#EEEEEEFF"
    }
    m.top.palette = palette
end function
