namespace PlaylistUtils
    function Open(contentNode as object, appController = invalid as object)
        playlistView = CreateObject("roSGNode", "PlaylistView")
        if appController = invalid
            appController = m.appController
        end if
        appController@.PushScreen(playlistView)
        playlistView@.BindNode()
        playlistView.content = contentNode
    end function
end namespace
