import "pkg:/source/utils/Types.bs"

function Init()
    m.top.observeField("checkedState", FuncName(OnCheckedStateChange))
end function

function OnValueChange()
    m.top.checkedState = [m.top.value]
end function

function OnCheckedStateChange() as void
    checkedState = m.top.checkedState
    if checkedState = invalid or checkedState.Count() = 0
        return
    end if
    m.top.value = checkedState[0]
end function
