namespace Tests

    @SGNode("ApplicationInfo")
    @suite
    class ApplicationInfoTests extends Rooibos.BaseTestSuite

        protected override function setup()
            m.ipAddressRegex = /\d+\.\d+\.\d+.\d+/
        end function

        protected override function beforeEach()
            m.node.service = new ApplicationInfo(m.top)
        end function

        @describe("ApplicationInfo")

        @it("Returns a valid local ip address")
        function _()
            ip = m.top@.GetLocalIpAddress()
            m.assertTrue(m.ipAddressRegex.IsMatch(ip))
        end function

        @it("Returns an invalid if no ip address is available")
        function _()
            m.node.service.roDeviceInfo = {
                GetIPAddrs: function() as dynamic
                    return []
                end function
            }

            ip = m.top@.GetLocalIpAddress()
            m.assertInvalid(ip)
        end function

    end class

end namespace
