namespace Tests

    @SGNode("InnertubeTestNode")
    @suite
    class NextParamsTests extends Rooibos.BaseTestSuite

        @describe("NextParams")

        @it("Encodes next params")
        function _()
            testCases = m.GetEncodingTestCases()
            for each testCase in testCases
                encoded = m.top@.Innertube_GetEncodedNextParams(testCase.input)
                m.assertEqual(encoded, testCase.encoded)
            end for
        end function

        function GetEncodingTestCases() as object
            return [{
                input: ["jNQXAC9IVRw", "9bZkp7q19f0"]
                encoded: "KgtqTlFYQUM5SVZSdyoLOWJaa3A3cTE5ZjA%3D"
            }]
        end function

    end class

end namespace
