namespace Tests

    @SGNode("SearchFiltersTestNode")
    @suite
    class SearchFiltersTests extends Rooibos.BaseTestSuite

        @describe("SearchFilters")

        @it("Encodes search filters")
        function _()
            testCases = m.GetEncodingTestCases()
            for each testCase in testCases
                encoded = m.top@.Innertube_GetEncodedSearchFilters(testCase.input)
                m.assertEqual(encoded, testCase.encoded)
            end for
        end function

        function GetEncodingTestCases() as object
            return [{
                input: {
                    "sort": "date"
                }
                encoded: "CAISAA%3D%3D"
            }, {
                input: {
                    "sort": "views"
                    "features": ["3d", "hd", "live"]
                }
                encoded: "CAMSBiABOAFAAQ%3D%3D"
            }, {
                input: {
                    "type": "playlist"
                }
                encoded: "EgIQAw%3D%3D"
            }]
        end function

    end class

end namespace
