function GetSha256(input as string) as string
    buffer = CreateObject("roByteArray")
    buffer.FromAsciiString(input)

    digest = CreateObject("roEVPDigest")
    digest.Setup("sha256")
    return digest.Process(buffer)
end function

function GetSha1(input as string) as string
    buffer = CreateObject("roByteArray")
    buffer.FromAsciiString(input)

    digest = CreateObject("roEVPDigest")
    digest.Setup("sha1")
    return digest.Process(buffer)
end function
