function ShowLoadingScreen()
    m.global.loadingIndicator.visible = true
end function

function HideLoadingScreen()
    loadingIndicator = m.global.loadingIndicator
    loadingIndicator.visible = false
    if loadingIndicator.hasField("message")
        loadingIndicator.message = ""
    end if
end function

function CopyLoadingMessagesToCache()
    CopyFile("libpkg:/config/loading-messages.json5", "cachefs:/loading_messages_v1.json")
end function
