namespace Tests

    @suite
    class StringUtilsTests extends Rooibos.BaseTestSuite

        @describe("StringUtils")

        @it("Checks if a string is null or empty")
        @params("test", false)
        @params("", true)
        @params(invalid, true)
        @params(-5, true)
        function _(obj as dynamic, expected as boolean)
            m.assertEqual(StringUtils.IsNullOrEmpty(obj), expected)
        end function

    end class

end namespace
