import "pkg:/source/asyncTask/asyncTask.bs"
import "FileTransportInitTask.bs"

function Init()
    m.buffer = CreateObject("roByteArray")

    DeleteFile(m.top.filenamePrevious)
    MoveFile(m.top.filename, m.top.filenamePrevious)
end function

function logItem(name as string, levelNum as integer, text as string) as void
    m.buffer.FromAsciiString(`[${name}] ${text}\n`)
    m.buffer.AppendFile(m.top.filename)
end function
