namespace AppManager

    function CaptureLastExitInfo(scene as object) as void
        manager = CreateObject("roAppManager")
        ' roAppManager.GetLastExitInfo() is only available on Roku OS 13 and above
        if FindMemberFunction(manager, "GetLastExitInfo") = invalid
            return
        end if
        lastExitInfo = manager.GetLastExitInfo()
        Logger.LogLastExitInfo(lastExitInfo)
        scene.lastExitInfo = lastExitInfo
    end function

end namespace
