namespace Http

    class RegistryApiRouter extends HttpRouter

        function new()
            super()

            m.Get("/api/registry", function(router as object, request as HttpRequest, response as HttpResponse) as boolean
                registryValues = RegistryUtils.ReadAll()
                response.Json(registryValues)
                return true
            end function)
        end function

    end class

end namespace
