import "pkg:/source/utils/CacheUtils.bs"

namespace Http

    class CacheRouter extends HttpRouter

        function new()
            super()
        end function

        @delete("/api/cache")
        function ClearCache(context as object) as boolean
            response = context.response

            CacheUtils.Clear()
            response.Default(204, "OK")
            return true
        end function

    end class

end namespace
