import "pkg:/source/utils/General.bs"
import "pkg:/source/utils/StringUtils.bs"

function Init()
    ip = GetLocalIpAddress()
    if ip = invalid 
        m.top.url = "(Could not get IP address: are we connected to the internet?)"
    else
        m.top.url = `http://${ip}:8888`
    end if
end function

function OnUrlSet()
    url = m.top.url

    qrCode = m.top.findNode("SettingsQRPoster")
    qrCode.text = url

    urlLabel = m.top.findNode("urlLabel")
    urlLabel.text = url
end function
