namespace Http

    class RegistryApiRouter extends HttpRouter

        function new()
            super()

            m.Get("/api/registry", function(context as object) as boolean
                response = context.response

                registryValues = RegistryUtils.ReadAll()
                response.Json(registryValues)
                return true
            end function)
        end function

    end class

end namespace
