namespace RokuYoutube.Utils
    ' Helper function convert seconds to mm:ss format
    ' getTime(138) returns 2:18
    function GetFormattedTime(length as integer) as string
        minutes = (length \ 60).ToStr()
        seconds = length mod 60
        if seconds < 10
            seconds = "0" + seconds.ToStr()
        else
            seconds = seconds.ToStr()
        end if
        return minutes + ":" + seconds
    end function
end namespace
