function Init()
end function

function OnkeyEvent(key as string, press as boolean) as boolean
    if press = false
        return false
    end if
    if key = "back"
        CloseVideo()
        return true
    end if
    return false
end function

function CloseVideo()
    homeGridScreen = m.top.getParent().findNode("HomeGridScreen")
    m.top.control = "stop"
    m.top.visible = false
    m.top.getParent().removeChild(m.videoPlayer)
    homeGridScreen.focus = true
end function
