const PROGRESS_WIDTH = 1144
const PROGRESS_HEIGHT = 6
const SEEK_HANDLE_WIDTH = 16
const SEEK_HANDLE_HEIGHT = 16

function Init()
    m.progressBar = m.top.findNode("ProgressBar")
    m.seekHandle = m.top.findNode("SeekHandle")
    OnProgressChange()
end function

function OnProgressChange()
    position = PROGRESS_WIDTH * m.top.progress
    m.progressBar.width = position
    m.seekHandle.translation = [position - SEEK_HANDLE_WIDTH / 2, (PROGRESS_HEIGHT - SEEK_HANDLE_HEIGHT) / 2]
end function
