import "pkg:/source/services/HttpClient.bs"

namespace ArabScript

    function Shape(text as string) as string
        request = HttpClient.PostJson("http://192.168.18.14:3000/shape", { text: text })
        response = request.Await()
        if not response.IsSuccess()
            return text
        end if

        json = response.Json()
        return json.shaped
    end function

end namespace
