import "pkg:/source/utils/Types.bs"

function Init()
    ' TODO:P2 make component disposable, and stop animation when component is disposed
    m.top.observeField("visible", FuncName(OnVisibleChanged))
    OnVisibleChanged()
end function

function OnVisibleChanged()
    Animate()
end function

function OnIndexSet()
    m.top.animationDelay = (m.top.index mod 5) * 0.2
    Animate()
end function

function Animate()
    m.top.animationControl = m.top.visible ? "start" : "stop"
end function
