import "pkg:/source/utils/Types.bs"

function Init()
    m.animation = m.top.findNode("loadingAnimation")
    m.top.observeField("visible", FuncName(OnVisibleChanged))
    OnVisibleChanged()
end function

function OnVisibleChanged()
    Animate()
end function

function OnIndexSet()
    m.animation.delay = (m.top.index mod 5) * 0.2
    Animate()
end function

function Animate()
    m.animation.control = m.top.visible ? "start" : "stop"
end function
