' TODO: this is being called from many places, including possibly background threads
' It should be made better than this
function FindAndGetPreferenceValues(keys as object) as object
    values = {}
    settings = m.top.getScene().findNode("SettingsScreen")
    if settings = invalid
        return values
    end if

    for each key in keys
        values[key] = settings@.GetPreferenceValue(key)
    end for
    return values
end function
