namespace Http

    class HttpSettings

        PackageName = "Playlet"
        Port = 8888
        MessagePort = invalid
        MaxConnections = 3
        Timeout = 60 * 1000
        MaxRequestLength = 4000
        Idletime = 60
        WwwRoot = "pkg:/"
        IndexName = "index.html"
        ServerName = "Playlet Server"

        function new(messagePort as object)
            m.MessagePort = messagePort
        end function

    end class

end namespace
