function StartTask(task as object, callback as object, metadata = invalid as object) as object
    if metadata = invalid
        ?"ERROR? no metadata"
        return invalid
    end if

    task = createObject("roSGNode", metadata.taskClass)
    task.functionName = metadata.functionName

    if metadata.hasOutput
        task.ObserveField("output", metadata.callback)
    end if

    task.control = "RUN"

    return task
end function
