namespace RokuYoutube.Http
  class HttpSettings

    PackageName = "Youtube for Roku"
    Port = 8888
    MessagePort = invalid
    MaxConnections = 3
    Timeout = 60
    MaxRequestLength = 4000
    Idletime = 60
    WwwRoot = "pkg:/"
    IndexName = "index.html"
    ServerName = "Roku Youtube Server"

    function new(messagePort)
      m.MessagePort = messagePort
    end function

  end class
end namespace