import "pkg:/source/utils/Logging.bs"

function ExecuteJob() as void
    input = GetInput()

    sleepTimeMs = ValidInt(input.sleep)
    if sleepTimeMs > 0
        Sleep(sleepTimeMs)
    end if

    if not input.success
        error = "Simulated job error for testing purposes"
        LogError(error)
        JobError(error)
        return
    end if

    LogInfo("Simulated job success for testing purposes")
end function
