import "pkg:/source/roku_modules/rokupromise/Promise.brs"

function Init()
    createTaskPromise("SettingsScreenTask", invalid).then(function(task as object)
        m.top.url = task.output.url
    end function)
end function

function OnUrlSet()
    url = m.top.url

    qrCode = m.top.findNode("SettingsQRPoster")
    qrCode.text = url

    urlLabel = m.top.findNode("urlLabel")
    urlLabel.text = url
end function
