import "Constants.bs"
import "pkg:/source/utils/Logging.bs"

@job("DownloadFontJob")
function ExecuteJob() as void
    urlTransfer = CreateObject("roUrlTransfer")
    urlTransfer.SetUrl(ARABIC_FONT_URL)
    urlTransfer.EnableEncodings(true)
    responseCode = urlTransfer.GetToFile(ARABIC_FONT_TMP_PATH)
    LogDebug(`Font download response code: ${responseCode}`)

    m.global.CellTitle1Font.uri = ARABIC_FONT_TMP_PATH
    m.global.CellTitle2Font.uri = ARABIC_FONT_TMP_PATH
end function
